### ISSUE TITLE
Add support for Cypress version 6

### ISSUE THREAD

**Issue by ashblox** [ngChile/ngchile-packages#18]
Hello,

I was trying to update Cypress in our app yesterday and it looks like since this package specifies version 5, I am now installing two versions of Cypress which I'd rather not do. Would you mind putting together a merge request to update that dependency? It [doesn't look like there were any breaking changes](https://docs.cypress.io/guides/guides/command-line#History) to the CLI options since 6 was released. I can also put a pull request together if that's easier.

Thank you!

![image](https://user-images.githubusercontent.com/47283036/112319226-3e13f880-8c84-11eb-838e-899a51d6ad9a.png)

**Comment by gpincheiraa** [comment]
Hi! I'm working in the update to version 2.0 of this schematics-library. Cypress to version 6.0 also.
I will notify to you in this issue when the new version were published.

**Comment by gpincheiraa** [comment]
@ashblox was added in version 1.1.1
I have been resolving a bug and I got the shoot for adding cypress 6 👍

**Comment by ashblox** [comment]
Thanks @gpincheiraa! Sorry for the late response - my GitHub is linked to an old email and I forgot to check in for responses. Will try it out tomorrow and let you know!

**Comment by ashblox** [comment]
@gpincheiraa Got things working just fine with the new version. Thanks again!

**Comment by gpincheiraa** [comment]
@ashblox Great!
