### ISSUE TITLE
How to use the .features file ?

### ISSUE THREAD

**Issue by noririco** [ngChile/ngchile-packages#8]
[bundled-features-files](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#bundled-features-files) from cypress-cucumber-preprocessor

is this posibble to use ?

**Comment by gpincheiraa** [comment]
Hi! yes! should be possible to use without problems. Are you been trying and it is not working?

**Comment by noririco** [comment]
Ok I tried to use and it seems ok, thanks.
